### ISSUE TITLE
Request: Better description as to where the option is turned on/off

### ISSUE THREAD

**Issue by RFBomb** [fieldOfView/Cura-ArcWelderPlugin#11]
Since this is by nature a post-processing script, I assumed it would be available in the post-processing script section of CURA. 
I was sitting here thinking that it had failed to properly install.

The only way I found out that it was inside of 'Special Modes' was by coming here and seeing someone else's issue about it not showing up in their 'special modes' section (issue was already closed). 

Please add a sentence or two to the main description on here and on the CURA Marketplace that tells users that it adds the toggle under the 'special modes' section in their settings menu. (If it already exists, then it wasn't apparent enough, because I missed it...)

Thanks for creating this wrapper. Worked well.

**Comment by b-morgan** [comment]
Please add some documentation on how to use this plugin.

**Comment by fieldOfView** [comment]
Added documentation here: b15b56bacff9388ab901c3c8cc2b622a20e22d15
