### ISSUE TITLE
Artifacts or settings issue?

### ISSUE THREAD

**Issue by Dan-imal** [fieldOfView/Cura-ArcWelderPlugin#20]
Small screw and nut.  One with Arc Welder Turned on and one with it off (I'm guessing you can figure out which is which).
![Comparison](https://user-images.githubusercontent.com/83475795/119166317-776ea780-ba2c-11eb-8d29-45b6758790b4.jpg)

Here's the settings.  They are what came pre-loaded.
![AW Settings](https://user-images.githubusercontent.com/83475795/119166431-9a00c080-ba2c-11eb-873f-343986737639.jpg)

Thank you

**Comment by seantapscott** [comment]
Hello there,

Always helpful to also list your printer name and firmware version.

**Comment by fieldOfView** [comment]
gcode files with and without ArcWelder turned on are also welcome to analyse the difference.

**Comment by Dan-imal** [comment]
Here's the GCode for my Ender 3v2
[nut & bolt 3.4m walls 20%inf 57m.zip](https://github.com/fieldOfView/Cura-ArcWelderPlugin/files/6524101/nut.bolt.3.4m.walls.20.inf.57m.zip)
Thank you.

**Comment by seantapscott** [comment]
G90 Influences Extruder should be turned on for Marlin. The longer arc
commands also cause trouble with the buffer size on board the mainboard.
Need to compile from the bugfix branch of marlin while enabling certain
values.

See this thread here for more info on upgrading firmware on Creality
printers:
https://github.com/FormerLurker/ArcWelderPlugin/issues/175#issuecomment-808851235

@ldursw found the solution.

**Comment by fieldOfView** [comment]
I'm closing this issue because it seems to be a combination of firmware and settings.
