### ISSUE TITLE
PlugIn "Arc Welder" will not start / load after update Cura 4.13.0b -> 4.13.0

### ISSUE THREAD

**Issue by SpRiNgToIfEl** [fieldOfView/Cura-ArcWelderPlugin#26]
1. Execute "Ultimaker_Cura-4.13.0-amd64.exe", check "deinstall old version" / "keep settings"
2. Start Cura, the PlugIn will not start / loaded.
3. activate the check-button, restart cura, same issue
4. deinstall PlugIn, reinstall PlugIn
5. Same issue as above
![1](https://user-images.githubusercontent.com/64694788/149310923-3932b0fa-487c-4718-8ce0-0820217101c1.jpg)
![2](https://user-images.githubusercontent.com/64694788/149310935-8d8f2064-6e08-440e-b0ce-61f8414bfee6.jpg)

**Comment by fieldOfView** [comment]
Please add the Cura.log log file. which can be found via Help -> Show configuration folder. Without it I cannot see why this is happening.

**Comment by SpRiNgToIfEl** [comment]
here the log-file.
[cura.log](https://github.com/fieldOfView/Cura-ArcWelderPlugin/files/7862046/cura.log)

**Comment by fieldOfView** [comment]
Thanks for the logs. I am looking into them now.

**Comment by fieldOfView** [comment]
It looks like there may be a dependency (dll) for the ArcWelder executable missing in your system.

Could you download the application "Dependencies" from https://lucasg.github.io/Dependencies/, extract that zip and run `DependenciesGui.exe`?

In the Cura configuration folder, go to `plugins\ArcWelderPlugin\ArcWelderPlugin\bin\win64` and drag and drop `ArcWelder.exe` into the DependencesGui window. Please post a screenshot of the window. That will tell us what is missing.

**Comment by SpRiNgToIfEl** [comment]
Attached the screenshot of DependencesGui

![arcwelder exe](https://user-images.githubusercontent.com/64694788/149350121-bbb60d30-2586-4925-adbb-93838beeecfd.jpg)

it looks like that "vcruntime140_1.dll" is missig?!

**Comment by fieldOfView** [comment]
In a previous version of the ArcWelder.exe build, the dependency was baked in ("statically linked"). As a quick workaround, download and extract [vcruntime140_1.zip](https://github.com/fieldOfView/Cura-ArcWelderPlugin/files/7863652/vcruntime140_1.zip), and put the dll in the same folder as ArcWelder.exe. Note that generally I would advice against downloading dlls from places. Alternatively, you may want to try installing the visual c runtime from here: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist

**Comment by blazewicz** [comment]
Any advice on how to fix this on other platforms? I have same issue on macOS.

**Comment by blazewicz** [comment]
Or maybe I'm facing a different issue with similar symptoms. I've checked 4.12.1 and ArcWelder plugin is also grayed-out. I'm running macOS on Apple Silicon chip, I guess binary isn't compatible with `arm64` arch.

**Comment by fieldOfView** [comment]
Probably a different issue with the same symptom. But it al starts with your cura.log.

**Comment by SpRiNgToIfEl** [comment]
> Or maybe I'm facing a different issue with similar symptoms. I've checked 4.12.1 and ArcWelder plugin is also grayed-out. I'm running macOS on Apple Silicon chip, I guess binary isn't compatible with `arm64` arch.



> In a previous version of the ArcWelder.exe build, the dependency was baked in ("statically linked"). As a quick workaround, download and extract [vcruntime140_1.zip](https://github.com/fieldOfView/Cura-ArcWelderPlugin/files/7863652/vcruntime140_1.zip), and put the dll in the same folder as ArcWelder.exe. Note that generally I would advice against downloading dlls from places. Alternatively, you may want to try installing the visual c runtime from here: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist

i have download the dll and copy it in the folder. arcwelder works now fine with cura 4.13.0.
thanks for your help!

why is the dll missing? Arcwelder worked great with cura 4.13.0b...

**Comment by fieldOfView** [comment]
> Arcwelder worked great with cura 4.13.0b...

Perhaps you had an older version of the ArcWelderPlugin installed before you installed Cura 4.13? Version 3.5.1 came with a version of the ArcWelder.exe that did not need the dll. Hopefully the next version of ArcWelder.exe will once again come "statically linked".

**Comment by fieldOfView** [comment]
@blazewicz, I cannot help you without logs...
