### ISSUE TITLE
"Out of Order" for Arcs, multiple artifacts and unnecissary moves

### ISSUE THREAD

**Issue by Snoman002** [fieldOfView/Cura-ArcWelderPlugin#31]
Cura 5.2.1
ArcWelder 3.6
Ender 3 v1 8bit

First tests with ArcWelder and noticed that it creates a rather disordered printing pattern on circles.  In short on a flat round sufrace printed with concentric top and bottom pattern the arc seem placed at random.  Ideal situation would be consecutive arcs working inward or outward, in this case it appears to randomly place the arcs resulting in the printer jumping from an arc near the middle, to an arc near the edge, to the very center, then back to the middle, then outside, then center, etc.

Image of the cura playback approximately half way through the first layer.

![image](https://user-images.githubusercontent.com/62316078/207467792-f82642d4-d2f2-418a-958e-3fb0f1800ea4.png)
Full first layer
![image](https://user-images.githubusercontent.com/62316078/207468637-22990438-fc9a-4e7d-98a6-79c6ba54bb57.png)

This obviously results in a very ugly layer (2nd or 3rd layer partially complete in this picture)
![image](https://user-images.githubusercontent.com/62316078/207467941-96931e90-9a23-452e-a50d-6ef10c610b5d.png)

[Arc Test.zip](https://github.com/fieldOfView/Cura-ArcWelderPlugin/files/10222923/Arc.Test.zip)

**Comment by seantapscott** [comment]
So you sliced it and then took the arcwelder-processed gcode and put it
into Cura to view the path?

**Comment by Snoman002** [comment]
This was the preview  in Cura while using the Cura ArcWelder plugin.

But...
I had not used concentric top and bottom layers in the newer version of Cura.  Previous use of concentric had it printing in order (outside in/inside out) as far as I remember thus I assumed the issue was in arc welder.  Testing cura now and it puts it out of order and ArcWelder is just following cura.
Frankly, I didn't even think that this was an issue out of Cura!

Cura with ArcWelder uninstalled
![image](https://user-images.githubusercontent.com/62316078/207488330-c2e25a95-4e7a-4f56-b2f2-e665c725eb5b.png)

**Comment by seantapscott** [comment]
Arcwelder doesn't do anything until you slice and then output.

**Comment by Snoman002** [comment]
uh, ok, sure.  thanks

**Comment by fieldOfView** [comment]
In addition to what @seantapscott said, the gcode viewer in Cura does not display curves. It just skips them in the viewer.
