### ISSUE TITLE
arc welder generates g3 with I=-0.000

### ISSUE THREAD

**Issue by PaintOnBrush** [fieldOfView/Cura-ArcWelderPlugin#33]
arc welder generated this line:

    G3 X68.406 Y115.000 I-0.000 J2.203 E0.04874

running it through the print fails with:

    G2/G3 requires IJ, IK or JK parameters

failed to run on my Klipper firmware / cancels print.

works when I change I-0.000 to I-0.001

**Comment by seantapscott** [comment]
I'm not certain, but it looks like this is a problem with Klipper not
accepting a zero I value. Reasons to have a 0 i value would be to create an
arc with a center at the current location.

Additionally, this is for the Cura Plugin, and not the ArcWelder library itself. FieldOfView does not directly maintain that library. 

https://github.com/FormerLurker/ArcWelderLib

**Comment by fieldOfView** [comment]
Closing this since it is not an issue with the plugin but with Arc Welder. This plugin is just the glue between Cura and Arc Welder.
