### ISSUE TITLE
Gcode results mutilate file

### ISSUE THREAD

**Issue by seantapscott** [fieldOfView/Cura-ArcWelderPlugin#8]
So the resultant post-processed file appears to mutilate my models.  What were supposed to be simple semi-circle arcs of 2mm thickness with filleted edges has these strange lines across the semi-circles' openings. 

![image](https://user-images.githubusercontent.com/20618832/104851798-163f9780-58c5-11eb-8612-07abeee2f897.png)

[WheelHolders.zip](https://github.com/fieldOfView/Cura-ArcWelderPlugin/files/5826561/WheelHolders.zip)

The slicer is Cura 4.8.0 for an Ultimaker 3E printer.  Slicer is set up for Griffin gcode flavor.  Arc Welder is enabled.
[UM3E_WheelHolders_43g_arcs.zip](https://github.com/fieldOfView/Cura-ArcWelderPlugin/files/5826562/UM3E_WheelHolders_43g_arcs.zip)

**Comment by seantapscott** [comment]
I realize that this project is just a wrapper for the original project, so I'm ok with just closing this if you like, and I'll open a case upstream. 

Sean

**Comment by fieldOfView** [comment]
To be honest, I don't expect much improvement in print quality on Ultimaker printers in the first place. G2/G3 support in the Ultimaker printers is vestigial at best. Also Cura does not display G2/G3 movements correctly. I'll try to improve the latter in future versions of the plugin.

**Comment by seantapscott** [comment]
I know Cura doesn't preview the arc code properly, but what it printed did have a strange line across the front of the semi-circle. Like I said, I tried reading through the gcode for ifgure out why, and I'm not really sure.  Just sharing an example if it might help at all. 

Thank  you again, love your support and investment.  Making the world a brighter place.

**Comment by fieldOfView** [comment]
I think it is best if you shared your result in the ArcWelderLib repository. I don't know enough about the inner workings of ArcWelder to say what is going on/wrong.

**Comment by seantapscott** [comment]
Here is my upstream "bug" report.  https://github.com/FormerLurker/ArcWelderPlugin/issues/126

I'm going to go ahead and guess this is a UM3 arc interpretation problem.  I was able to install Simplify3D and get a preview of the gcode, and it look accurate, though there was a skirt running through it without the proper offset applied in the preview. 
![image](https://user-images.githubusercontent.com/20618832/105087939-3b6d0b00-5a69-11eb-9db8-e4b3f540e0a1.png)

**Comment by fieldOfView** [comment]
Since the linked ArcWelderLib issue is closed, I'm closing this one too.
